baseurl = "https://notesfromthelifeboat.com/"
languageCode = "en-us"
title = "Notes from the Lifeboat"
theme = "hugo-type-theme"
# Enable comments by entering your Disqus shortname
disqusShortname = "notesfromthelifeboat"
# Add your tracking code to enable Google Analytics
googleAnalytics = "UA-27980065-1"
# Posts per page
paginate = 10
# Comment the themesDir option if you use this theme in production
# themesDir = "../.."
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
	author = "Ian Firkin"
	description = "Dim interlocutions"
	# The keywords will be added as a meta tag. Delimit them with a comma.
	keywords = ""
	# Either show custom avatar on the top
	# left by adding the filename in below
	avatar = "img/avatar.png"
	# or use Gravatar by adding your email address to generate a unique avatar
	# gravatar = "your@email.com"

	#headerText = ""
	# To add a header background to the main site, save your image under static/img/.
	# If now image path is provided, a orange background will be shown instead.
	# headerImage = ""
	copyright = "Released under the MIT license<br>Powered by [Hugo](//gohugo.io/) with the [Type Theme](//github.com/digitalcraftsman/hugo-type-theme)"

	[params.social]
		# Insert your accout name and the icon will be shown in the right menu
		rss = true
		homepage = true
		email = "ian.firkin@gmail.com"
		github = "lobsteropteryx"
		twitter = "lobsteropteryx"

